# Generated by Django 5.0.4 on 2024-05-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
