# Generated by Django 5.0.4 on 2024-05-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
