# Generated by Django 5.0.4 on 2024-05-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
